# This is the default configuration for Barista and is required to run artifacts and local instances.
# This file is NOT required in Docker environments, please use environment variables instead
# For usage and examples refer to the wiki page at https://barista.evyn.me/configuration

[API]
token = "Nzk5NzIwMTM4MTk4NjE0MDg4.YAHraw.RAJOGve-ziNytlzeY5C61worgHw"

[Defaults]
prefix = "g."
embeds = true
maintainer_ids = ["481789273198273"]

[Datasource]
enabled = true
type = "sqlite"
ip = ""
port = ""
database = ""
user = ""
password = ""